### ISSUE TITLE
keyPrefix not added to baseUri

### ISSUE THREAD

**Issue by Lemmork** [flownative/flow-aws-s3#29]
I'm using version 2.0.4 with Neos 4.3.7 and configured it like this:
```
Flownative:
  Aws:
    S3:
      profiles:
        default:
          credentials:
            key: 'mykey'
            secret: 'mysecret'
          region: 'eu-central-1'
  Flow:
    resource:
      collections:
        persistent:
          target: 'awsPersistentResourcesTarget'
      targets:
        awsPersistentResourcesTarget:
          target: 'Flownative\Aws\S3\S3Target'
          targetOptions:
            bucket: 'klosterfrau-dev-file-storage'
            keyPrefix: 'my_project/persistent/'
            baseUri: 'https://mycloudfront.cloudfront.net/'
```

I would expect, that the urls will be generated like this:
https://mycloudfront.cloudfront.net/my_project/persistent/<hashkey>/filename.jpg
but the keyPrefix part is missing and the generated path looks like this:
https://mycloudfront.cloudfront.net/<hashkey>/filename.jpg

I migrated from flow-google-cloudstorage and there the Resource link was created with the keyPrefix.
